### ISSUE TITLE
Remove `v` in version

### ISSUE THREAD

**Issue by sodre** [conda-forge/vault-feedstock#28]
Hi @adbeda,

Can you remove the `v` in version. I did not catch it when I reviewed your previous PR.

Don't forget you need to make the changes in your fork the vault-feedstock repo, and issue a PR. Otherwise, the build-bots will push things incorrectly to anaconda.org.

https://github.com/conda-forge/vault-feedstock/blob/2c4db338ce989031691bb95eb45face87d09f4d1/recipe/meta.yaml#L9

**Comment by adbeda** [comment]
got it. should I pull the changes you just made to the recipe, first?

**Comment by sodre** [comment]
no, those are still work-in-progress
